---
- name: elasticsearch servers
  ec2:
    key_name: baba
    instance_type: m3.2xlarge
    image: emi-2a255279
    instance_tags:
      index: elasticsearch
      service: elasticsearch
    count_tag:
      index: elasticsearch
    exact_count: 1
    group:
      - default
      - elasticsearch
    monitoring: true
    volumes:
      - device_name: /dev/sda
        volume_size: 15
        delete_on_termination: true
      - device_name: /dev/vdb
        volume_size: 500
        delete_on_termination: true
    assign_public_ip: no
    addressing_type: private
  register: ec2

- name: Add new instance to host group
  add_host: groups=tag_index_elasticsearch name={{ item.public_dns_name }}
  with_items: '{{ ec2.instances }}'
