---
- name: Install PHP
  apt: "name={{ item }} state=installed"
  with_items:
    - php7.0-cli
    - php7.0-intl
    - php7.0-mcrypt
    - php7.0-curl
    - php7.0-bcmath
    - php7.0-mbstring
    - php7.0-xml
    - php7.0-mysql
  become: true
