---
- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=86400
  become: true

- apt: name=ntp state=installed
  become: true

- name: Get software for Python-based control.
  apt: "name={{ item }} state=installed"
  with_items:
    - curl
    - python-apt
    - python-pycurl
    - sudo
    - unzip
  become: true
