---
- apt: update_cache=yes
  become: true

- apt: "name={{ item }} state=installed"
  with_items:
    - aptitude
    - curl
    - ntp
    - python-apt
    - python-pycurl
    - sudo
    - unzip
  become: true

- apt: upgrade=yes
  become: true

- template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf
  become: true
