---
- apt: update_cache=yes
  become: true

- apt: "name={{ item }} state=installed"
  with_items:
    - aptitude
    - curl
    - ntp
    - python-apt
    - python-pycurl
    - sudo
    - unzip
  become: true

- apt: upgrade=yes
  become: true

- lineinfile:
    dest: /etc/dhcp/dhclient.conf
    line: 'supersede domain-name-servers 127.0.0.1;'
    state: present
  become: true
  notify: restart networking
