---
- apt: update_cache=yes
  become: true

- apt: "name={{ item }} state=installed"
  with_items:
    - aptitude
    - curl
    - ntp
    - python-apt
    - python-pycurl
    - sudo
    - unzip
  become: true

- apt: upgrade=yes
  become: true

- lineinfile: dest=/etc/dhcp/dhclient.conf line='supersede domain-name-servers {{ hostvars[item].ec2_private_ip_address }};' state=present
  with_items: '{{ groups[''tag_bastion_True''] }}'
  when: hostvars[item].ec2_private_ip_address is defined
  become: true

- lineinfile: dest=/etc/dhcp/dhclient.conf line='supersede domain-name "kal3a.tld";' state=present
  become: true
  notify: restart networking
