---

- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars.yml
  tasks:
    - name: security group default
      ec2_group:
        name: default
        description: default group
        rules:
          - proto: icmp
            from_port: -1
            to_port: -1
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: security group www
      ec2_group:
        name: www
        description: opens web ports
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0

    - name: security group www
      ec2_group:
        name: couchdb
        description: couchdb servers
        rules:
          - proto: tcp
            from_port: 5986
            to_port: 5986
            cidr_ip: 0.0.0.0/16
          - proto: tcp
            from_port: 5984
            to_port: 5984
            cidr_ip: 0.0.0.0/16

    - name: security group www
      ec2_group:
        name: rabbitmq
        description: services supporting runtime and admin of rabbitmq
        rules:
          - proto: tcp
            from_port: 4369
            to_port: 4369
            cidr_ip: 0.0.0.0/16
          - proto: tcp
            from_port: 5672
            to_port: 5672
            cidr_ip: 0.0.0.0/16
          - proto: tcp
            from_port: 15672
            to_port: 15672
            cidr_ip: 0.0.0.0/16
          - proto: tcp
            from_port: 25672
            to_port: 25672
            cidr_ip: 0.0.0.0/16

    - name: couchdb servers
      ec2:
        key_name: baba
        instance_type: m3.xlarge
        image: emi-2a255279
        instance_tags:
          db: couchdb
        count_tag:
          db: couchdb
        exact_count: 1
        group:
          - default
          - couchdb
        monitoring: true
        volumes:
          - device_name: /dev/sda
            volume_size: 15
            delete_on_termination: true
          - device_name: /dev/vdb
            volume_size: 100
            delete_on_termination: true
        wait: true
      register: ec2

    - name: Add new instance to host group
      add_host: groups=tag_db_couchdb name={{ item.public_dns_name }}
      with_items: '{{ ec2.instances }}'

    - name: rabbitmq servers
      ec2:
        key_name: baba
        instance_type: m3.xlarge
        image: emi-2a255279
        instance_tags:
          queue: rabbitmq
        count_tag:
          queue: rabbitmq
        exact_count: 1
        group:
          - default
          - rabbitmq
        monitoring: true
        volumes:
          - device_name: /dev/sda
            volume_size: 15
            delete_on_termination: true
        wait: true
      register: ec2

    - name: Add new instance to host group
      add_host: groups=tag_queue_rabbitmq name={{ item.public_dns_name }}
      with_items: '{{ ec2.instances }}'

- name: configure couchdb
  hosts: tag_db_couchdb
  remote_user: debian
  gather_facts: False
  tasks:
    - name: waiting for ssh
      local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH
    - name: format devices
      filesystem: fstype=ext3 dev=/dev/vdb
      become: true
