---
- name: couchdb servers
  ec2:
    key_name: baba
    instance_type: m3.xlarge
    image: emi-2a255279
    instance_tags:
      db: couchdb
      service: couchdb
    count_tag:
      db: couchdb
    exact_count: 3
    group:
      - default
      - couchdb
      - consul
    monitoring: true
    volumes:
      - device_name: /dev/sda
        volume_size: 15
        delete_on_termination: true
      - device_name: /dev/vdb
        volume_size: 1000
        delete_on_termination: true
    assign_public_ip: no
  register: ec2
