---
- name: format devices
  filesystem: fstype=ext3 dev=/dev/vdb
  become: true

- name: mount devices
  mount:
    name: /var/lib/elasticsearch
    src: /dev/vdb
    fstype: ext3
    state: mounted
  become: true

- name: Install Elasticsearch
  apt: "name={{ item }} state=installed"
  with_items:
    - elasticsearch
  become: true

- lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host'
    line: "network.host: {{ hostvars[ansible_ssh_host]['PrivateIpAddress'] }}"
  become: true
  notify: restart elasticsearch

- consul:
    service_name: elasticsearch
    service_port: 9200
