---
- name: Add elastic GPG key to debian
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch id=d27d666cd88e42b4
  become: true

- name: Add elastic sources to apt.
  apt_repository: repo='{{ item }}' state=present filename='elastic-5.x'
  with_items:
    - deb https://artifacts.elastic.co/packages/5.x/apt stable main
  become: true
