---
- name: Add erlang to apt.
  apt_repository: repo='{{ item }}' state=present filename='erlang-solutions'
  with_items:
    - deb https://packages.erlang-solutions.com/debian jessie contrib
  become: true

- name: Add erlang GPG key to debian
  apt_key: url=https://packages.erlang-solutions.com/debian/erlang_solutions.asc id=434975BD900CCBE4F7EE1B1ED208507CA14F4FCA
  become: true
