---
# Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
# Will include all hosts the playbook is run on.
# Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html

- apt: "name={{ item }} state=installed"
  with_items:
    - git
    - php5-cli
    - php5-ssh2
    - python-dev
    - python-pip
    - rsync
  become: true

- pip: name=ansible
  become: true

- synchronize:
    src: "{{ playbook_dir }}/../"
    dest: "{{ ansible_env['HOME'] }}/cloud"
    delete: true
    rsync_opts:
      - "--exclude=vendor_roles"
      - "--exclude=.vagrant"
