---
- name: Install PHP and Apache2
  apt: "name={{ item }} state=installed"
  with_items:
    - apache2
    - php7.0-fpm
    - php7.0-cli
    - php7.0-intl
    - php7.0-mcrypt
    - php7.0-curl
    - php7.0-bcmath
    - php7.0-mbstring
    - php7.0-xml
    - php7.0-mysql
  become: true

- name: enable proxy module in apache
  apache2_module: 'state=present name={{ item }}'
  with_items:
    - proxy_fcgi
    - expires
    - headers
  become: true
  notify:
    - restart apache2

