---
- user:
    name: consul
    home: /opt/consul
    system: yes
    shell: /bin/false
    createhome: no
  become: true
- apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  become: true
  with_items:
    - git
    - jq
    - curl
    - runit
    - unzip
    - python-pip
- pip:
    name: python-consul
  become: true

- file:
    path: "{{ item }}"
    state: directory
  become: true
  with_items:
    - /opt/consul
    - /etc/consul.d
    - /etc/sv/consul
    - /etc/sv/consul/log

- file:
    path: "{{ item }}"
    owner: consul
    state: directory
  become: true
  with_items:
    - /var/log/consul
    - /var/consul

- get_url:
    url: https://checkpoint-api.hashicorp.com/v1/check/consul
    dest: /tmp/check_consul

- shell: cat /tmp/check_consul | jq .current_version --raw-output
  register: check_consul

- get_url:
    url: https://releases.hashicorp.com/consul/{{ check_consul.stdout }}/consul_{{ check_consul.stdout }}_linux_amd64.zip
    dest: /tmp

- unarchive:
    src: /tmp/consul_{{ check_consul.stdout }}_linux_amd64.zip
    dest: /opt/consul
    remote_src: yes
  become: true

- file:
    path: /tmp/consul_{{ check_consul.stdout }}_linux_amd64.zip
    state: absent
  become: true

- file:
    path: /opt/consul/consul
    mode: a+x
    owner: consul
  become: true

- template:
    src: templates/consul/run.j2
    dest: /etc/sv/consul/run
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  become: true

- template:
    src: templates/consul/log/run.j2
    dest: /etc/sv/consul/log/run
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  become: true
  notify: restart consul

- runit:
    service_dir: /etc/service
    name: consul
    state: started
    enabled: yes
  become: true

# iptables -t nat -A PREROUTING          -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
# iptables -t nat -A PREROUTING          -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
- iptables:
    table: nat
    chain: PREROUTING
    protocol: "{{ item }}"
    match: "{{ item }}"
    destination_port: 53
    jump: REDIRECT
    to_ports: 8600
  with_items:
    - udp
    - tcp
  become: yes

# iptables -t nat -A OUTPUT -d localhost -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
# iptables -t nat -A OUTPUT -d localhost -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600

- iptables:
    table: nat
    chain: OUTPUT
    destination: localhost
    protocol: "{{ item }}"
    match: "{{ item }}"
    destination_port: 53
    jump: REDIRECT
    to_ports: 8600
  with_items:
    - udp
    - tcp
  become: yes
