---
- name: install rabbitmq
  apt: name=rabbitmq-server state=installed force=yes

- name: enable rabbitmq plugins
  rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing,rabbitmq_federation state=enabled
  notify:
  - restart rabbitmq

- name: add users
  rabbitmq_user: user={{item}} password=changeme tags=administrator,{{item}} vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present
  with_items:
  - user1
  - user2

- name: remove default guest user
  rabbitmq_user: user=guest state=absent

- name: ensure vhost /test is present
  rabbitmq_vhost: name=/test state=present

#- name: set federation local-username
#  rabbitmq_parameter: component=federation name=local-username value='"user1"' state=present

- include: handlers/main.yml

- consul:
    service_name: rabbitmq
    service_port: 5672
