---
- apt: "name={{ item }} state=installed"
  with_items:
    - bind9
    - bind9utils
    - bind9-doc
  become: true

- template: src=roles/bind/templates/db.{{ item.name }}.j2 dest=/etc/bind/db.{{ item.name }}
  with_items:
    - name: kal3a.tld
    - name: 10.1.3.in-addr.arpa
  become: true
  notify: reload bind

- template:
    src: templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  become: true
  notify: reload bind

- lineinfile: dest=/etc/bind/named.conf.local line='zone "{{ item.name }}"  { type master; file "/etc/bind/db.{{ item.name }}"; };' state=present
  with_items:
    - name: kal3a.tld
    - name: 10.1.3.in-addr.arpa
  become: true
  notify: reload bind
