---
- apt: update_cache=yes
  become: true

- apt: name={{ item }}
  with_items:
    - python-pip
    - rsync
    - ntp
    - git
  become: true

- pip: name=ansible
  become: true

- synchronize:
    src: "{{ playbook_dir }}"
    dest: "{{ ansible_env['HOME'] }}"
    delete: true
    rsync_opts:
      - "--exclude=vendor_roles"
