---
- name: Install PHP and Apache2
  apt: "name={{ item }} state=installed"
  with_items:
    - apache2
    - php7.0-fpm
  become: true

- name: enable proxy module in apache
  apache2_module: 'state=present name={{ item }}'
  with_items:
    - proxy_fcgi
    - expires
    - headers
  become: true
  notify:
    - restart apache2
