---
- include: init-debian.yml

# Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
# Will include all hosts the playbook is run on.
# Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html

- block:
  - lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ec2_private_ip_address }} {{hostvars[item].ec2_private_dns_name}}" state=present
    with_items: '{{ groups[''all''] }}'
    name: "Build hosts file"
    when: hostvars[item].ec2_private_ip_address is defined
    become: true
