---
- name: waiting for ssh
  local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH

- name: format devices
  filesystem: fstype=ext3 dev=/dev/vdb
  become: true

- name: mount devices
  mount:
    name: /var/lib/elasticsearch
    src: /dev/vdb
    fstype: ext3
    state: mounted
  become: true

- name: Install Elasticsearch
  apt: "name={{ item }} state=installed"
  with_items:
    - elasticsearch
  become: true

