---
- name: deploy Elasticsearch
  hosts: index_elasticsearch
  remote_user: debian
  roles:
    - role: debian
      elastic: true
    - role: ansiblebit.oracle-java
      oracle_java_set_as_default: yes
    - role: elasticsearch
