---
- hosts: worker_*
  vars_files:
    - vars.yml
  remote_user: debian
  roles:
    - role: common
    - role: debian
      dotdeb: true
    - role: worker
    - role: supervisor
    - role: composer
    - role: kal3a

- hosts: worker_consumer
  vars_files:
    - vars.yml
  remote_user: debian
  roles:
    - role: worker-consumer

- hosts: worker_streaming
  vars_files:
    - vars.yml
  remote_user: debian
  roles:
    - role: worker-streaming
