---
# This playbook deploys the whole application stack in this site.

#- environment:
#    PATH: "{{ ansible_env.PATH | default }}:/home/debian/bin"

- name: apply common configuration to all nodes
  hosts: all
  gather_facts: no
  vars_files:
    - vars.yml
  remote_user: debian

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  gather_facts: no
  vars_files:
    - vars.yml
  remote_user: debian

  roles:
    - role: debian
      dotdeb: true
    - role: web

- name: deploy MySQL and configure the databases
  hosts: db_mysql
  gather_facts: no
  vars_files:
    - vars.yml
  remote_user: debian

  roles:
    - role: db

- name: deploy RabbitMQ
  hosts: queue_rabbitmq
  gather_facts: no
  vars_files:
    - vars.yml
  remote_user: debian

  roles:
    - role: debian
      rabbitmq: true
      erlang: true
    - role: rabbitmq
      become: true

- name: deploy CouchDB
  hosts: db_couchdb
  gather_facts: no
  remote_user: debian
  vars_files:
    - vars.yml
  roles:
    - couchdb

- name: deploy Elasticsearch
  hosts: index_elasticsearch
  remote_user: debian
  vars_files:
    - vars.yml
  roles:
    - role: debian
      elastic: true
    - role: ansiblebit.oracle-java
      oracle_java_set_as_default: yes
    - role: elasticsearch

- hosts: worker_*
  vars_files:
    - vars.yml
  remote_user: debian
  roles:
    - role: debian
      dotdeb: true
    - role: worker
    - role: supervisor
    - role: composer
    - role: kal3a

- hosts: worker_consumer
  vars_files:
    - vars.yml
  remote_user: debian
  roles:
    - role: worker-consumer

- hosts: worker_streaming
  vars_files:
    - vars.yml
  remote_user: debian
  roles:
    - role: worker-streaming
