---
- name: deploy web
  hosts: web_apache
  vars_files:
    - vars.yml
  remote_user: debian
  roles:
    - role: common
    - role: consul
    - role: debian
      dotdeb: true
      nodejs: true
    - role: web
    - role: composer
    - role: kal3a
    - role: nodejs
    - role: kal3a-tags
    - role: kal3a-search
    - role: kal3a-web
