---
- hosts: localhost:!all
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml
  roles:
    - eucalyptus-groups
    - worker-eucalyptus

- hosts: tag_worker_*
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml
  remote_user: debian
  tasks:
    - local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=10

- hosts: tag_worker_*
  vars_files:
    - vars.yml
  remote_user: debian
  roles:
    - role: common
    - role: debian
      dotdeb: true
    - role: worker
    - role: supervisor
    - role: composer
    - role: kal3a

- hosts: tag_worker_consumer
  vars_files:
    - vars.yml
  remote_user: debian
  roles:
    - role: worker-consumer

- hosts: tag_worker_streaming
  vars_files:
    - vars.yml
  remote_user: debian
  roles:
    - role: worker-streaming
