---
- name: deploy web
  hosts: web_apache
  vars_files:
    - vars.yml
  remote_user: debian
  roles:
    - role: common
    - role: debian
      nodejs: true
    - role: web
    - role: nodejs
    - role: kal3a-search
